config/routes.rb
MoolahMeerkat::Application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get]
  match 'auth/failure', to: redirect('/'), via: [:get]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get]
  
  root 'welcome#index'
  

  resources :users, except: [:index] do
    resources :activities, only: [:index]
    collection do
      get 'search'
    end

    resources :achievements, only: [:index, :show] do
    end

    resources :goals do
      resources :transactions do
      end
    end

    resources :connections, only: [:create, :index, :destroy] do
    end

  end
end

app/models/user.rb
class User < ActiveRecord::Base
  
  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true
  has_and_belongs_to_many :goals
  has_many :achievements
  has_many :transactions
  has_many :connections
  has_many :friends, :through => :connections

  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.email = auth.info.email
      user.photo_url = auth.info.image
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

#Returns an integer of how many acheievements the user has won
  def penguin
    Achievement.where(user_id: id, name: "Penguin").count 
  end

  def meerkat
  Achievement.where(user_id: id, name: "Meerkat").count    
  end

  def gorilla
    Achievement.where(user_id: id, name: "Gorilla").count
  end

  def yak
    Achievement.where(user_id: id, name: "Yak").count
  end
#Users total savings
  def total_savings
    self.transactions.inject(0) { |total, transaction| total + transaction.amount }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticated!, :current_user

  def show
    @user = User.find(params[:id])
    @all_activities = PublicActivity::Activity.order("created_at desc").limit(15).all  
  end

  def destroy
  end
  
  def search
    query = params[:query].split(" ").each {|name| name.capitalize!}
    if query[1].nil?
      query << 'none'
    end
    @users = User.where("first_name='#{query[0]}' OR last_name='#{query[1]}'") 
  end

private

  def set_user
    @user = User.find(params[:id])
  end

end

app/views/users/search.html.erb
<div class="mural" style="background: url(<%= random_background %>)"></div>

<div class="well results">
<% if @users.length == 0 %>
  <p>We couldn't find that user. Either do a better job of searching or send them an invite below!</p>
  <!-- insert form for sending an invitation via email -->
<% else %>
  <ul>
    <% @users.each do |user| %>
      <li><img src=<%= user.photo_url %>> <%= link_to "#{user.first_name} #{user.last_name}", user_path(user.id)  %></a></li>
    <% end %>
  </ul>
<% end %>
</div>

app/views/users/show.html.erb
<div class="mural" style="background-color: lightcyan !important"></div>
<div class="container">
  
  <span class="huh" style="margin-bottom: 40px !important;">
    <img style="margin-top: 100px !important;display:inline" src="<%= @user.photo_url %>"> &nbsp &nbsp
    <h1 style="display:inline;position:relative;top:60px;"><%= @user.first_name %> <%= @user.last_name %></h1>
    <% if @current_user.id != @user.id && !(@current_user.friends.pluck(:id).include?(@user.id)) %>
      <%= button_to "Add Friend", user_connections_path(@current_user, friend_id: @user.id), method: 'post', class: "btn btn-primary frand" %>
    <% end %>
  </span>
  <h2>Total Savings: <span class="label label-default" style="background-color: #FF4500 !important;">$<%= number_with_delimiter(@user.total_savings) %></span></h2>

  <div style="width: 95%; border-bottom: dotted 2px gray; margin-bottom: 35px !important"></div>




  <h2>Badges earned:</h2>
     <div class="well" style="background: none; border: none !important; position: relative !important; bottom: 40px;">
 <div style="float:left;">
   
   <img src="https://dl.dropboxusercontent.com/u/23639721/Penguin.gif" width= "200">
   <p><span class="label label-default" style="background-color: #FF4500 !important;">x <%= @current_user.penguin %> </span></p>
 </div>
       <div style="float:left";>
         <img src="https://dl.dropboxusercontent.com/u/23639721/Meerkat.gif"width= "200">
         <p><span class="label label-default" style="background-color: #FF4500 !important;">x <%= @current_user.meerkat %></span></p> 
       </div> 
        <div style="float:left";>
          <img src="https://dl.dropboxusercontent.com/u/23639721/Gorilla.gif"width= "200">
          <p><span class="label label-default" style="background-color: #FF4500 !important;">x <%= @current_user.gorilla %></span></p> 
        </div>
          
          <div>
          <img src="https://dl.dropboxusercontent.com/u/23639721/Yak.gif" alt=""width= "200"> 
          <p><span class="label label-default" style="background-color: #FF4500 !important;">x <%= @current_user.yak %></span></p>  
          </div>    
            

      </div>


        <div style="width: 95%; border-bottom: dotted 2px gray; margin-bottom: 35px !important"></div>


<% unless @user.goals.length == 0 %>

  <h2>Goals:</h2>  

      <div class="well" style="margin-top: 20px !important">
                <center>

      <% @user.goals.each do |goal| %>    
          <div class"tiles" style="background: url(<%= goal.photo_url %>); height: 200px; width: 200px; background-size: cover; display: inline-block !important">
          <ul class="lolwut" style="background-color: rgba(255, 255, 255, 0); height: 200px; width: 200px">
            <span class="wtf">
              <li><strong>Goal:</strong></li> 
              <li><%= goal.name %></li>
              <br/> 
              <li><strong>Description:</strong></li>
              <li><%= goal.description %></li>
              <li>by <%= goal.deadline %></li>
              <br/>
              <li><strong>Current savings:</strong></li> 
              <li>$<%= goal.balance(@user.id) %></li>
            </span>
          </ul>

        </div>
      <% end %>
      </center>

    </div>

  <% end %>

    <div style="width: 95%; border-bottom: dotted 2px gray; margin-top: 80px !important;margin-bottom: 35px !important"></div>


   <h2>News Feed</h2>


<ul style="position:relative! important; left: 80px;" class= "Newsfeed">
  <%= render_activity(@all_activities)%>
</ul>

    <div style="width: 95%; border-bottom: dotted 2px gray; margin-top: 80px !important;margin-bottom: 35px !important"></div>

<!-- Friend Connections -->
    <h2><%= @user.first_name %>'s Friends</h2>
    <ul>
      <% @user.connections.each do |connection| %>
        <li><img src="<%= connection.friend.photo_url %>">   <%= link_to "#{connection.friend.first_name} #{connection.friend.last_name}", user_path(connection.friend_id) %></li>
      <% end %>
    </ul>
    <div class="tiles"></div>
</div>
</div>