config/routes.rb
MoolahMeerkat::Application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get]
  match 'auth/failure', to: redirect('/'), via: [:get]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get]
  
  root 'welcome#index'
  

  resources :users, except: [:index] do
    resources :activities, only: [:index]
    collection do
      get 'search'
    end

    resources :achievements, only: [:index, :show] do
    end

    resources :goals do
      resources :transactions do
      end
    end

    resources :connections, only: [:create, :index, :destroy] do
    end

  end
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :name, :final_amount, :deadline, presence: true
  has_and_belongs_to_many :users
  has_many :transactions


  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }

  # logic for calculating total transaction amount
  def balance(id)
    self.transactions.where(user_id: id).sum(:amount)
  end

  # logic for an individual's goal within a group goal.
  def individual_final_amount
    self.final_amount / self.users.length
  end

  # this has to do with achievements
  def progress_as_float(user)
    progress = (balance(user.id).to_f / (self.final_amount / self.users.length)) * 100
  end

  def progress
    colors = ["red", "orange", "violet", "pink", "yellow", "lightcyan", "purple", "darkgoldenrod", "green", "blue"]
    count = 0
    progress = {}
    self.users.each do |user|
      individual_progress = (balance(user.id).to_f / self.individual_final_amount) * 100
      progress[user.id] = {:individual_progress => "#{individual_progress}%", :color => colors[count], :individuals_progress_for_goal => "#{individual_progress / self.users.length}%" }
      count +=1
    end
    return progress
  end

  def transform_date
    d = Date.parse(self.deadline.to_s)
    return "#{Date::MONTHNAMES[d.mon]} #{d.mday}, #{d.year}"
  end


end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

before_action :authenticated!, :current_user

  def new
    @goal = Goal.new

    render :new
  end

  def create
    @goal = Goal.new(goal_params)
    # add new goal to the current user
    if @goal.save
      params.keys.each do |x|
        if x.to_i > 0
          User.find(x.to_i).goals << @goal
        end
      end
      @current_user.goals << @goal

      redirect_to user_goal_path(current_user, @goal)
    else
      redirect_to new_user_goal_path(current_user)
    end
  end

  #old achievements help pass a object on load so we can check the before an after 
  #status on each transaction in order to tell if an achievement has been won
  def show
    @user = User.find(params[:user_id])
    @goal = @user.goals.find(params[:id])
    @oldAchievement = Achievement.where(user: @user, goal: @goal)
  end

  def index
    @goal = Goal.all
  end

  def update
    redirect_to user_path
  end

  def edit
  end

  def destroy
  end

  private

  def goal_params
    params.require(:goal).permit(:name, :description, :photo_url, :deadline, :final_amount)
  end


end

app/views/goals/_form.html.erb
<div class="well">
<%= form_for [@current_user, @goal], :action => :create, :html => {:class => 'form',:role => 'form'} do |f| %>
  <div class="form-group">
    <%= f.label :name %></br>
    <%= f.text_field :name, :class => 'field' %></br>
  </div>

  <div class="form-group">
    <%= f.label :description %></br>
    <%= f.text_field :description, :class => 'field' %></br>  
  </div>

  <div class="form-group">
    <%= f.label :photo_url %></br>
    <%= f.text_field :photo_url, :class => 'field' %></br>  
  </div>

  <div class="form-group">
    <%= f.label :final_amount %></br>
    <%= f.text_field :final_amount, :class => 'field' %></br>
  </div>

  <div class="form-group">
    <%= f.label :deadline %></br>
    <%= f.date_field :deadline, :class => 'field' %></br>
  </div>

  <h4>Add your friends to this goal:</h4>
      <% @current_user.friends.each do |friend| %>
   <div class="checkbox" style="text-align: left !important; position: relative !important; left: 250px">
     <label>
       <%= "#{friend.first_name} #{friend.last_name}" %> 
       <input type="checkbox" class="input_checkbox" name="<%= friend.id %>" value="blah" style="display:block" style="position: relative !important; left: 80px">
     </label>
    </div>
    <% end %>
  

 <br>
 <br>
  <%= f.submit nil, class: "btn btn-primary" %>
<% end  %> 
  
</div>

app/views/goals/_form_group.html.erb
# user.connections.each do |connection|
# a list of all connections by name. 
# a button for each connection to be added to the group. 
<%= link_to "Add to goal", user_connections_path(:friend_id => user), :method => :post %>

app/views/goals/index.html.erb
<br>
<br>
<br>
<br>



<h1 style= "margin: 0 auto; width: 500px; padding:5px;">All Of Your Goals <%= @current_user.first_name %></h1>

<ul style="float:left;">
  <% @current_user.goals.each do |goal| %>
  <li style="display:inline; padding:10px;"><%= link_to goal.name, user_goal_path(@current_user.id, goal.id) %></li>
  <% end %>
</ul>

app/views/goals/new.html.erb
<div class="mural" style="background: url(<%= random_background %>)"></div>
  <div class="container">

  <h2>Create new goal</h2>
  <%= render "form" %>

</div>

app/views/goals/show.html.erb
<div class="container">
<!-- <div class="row"> -->

<div class="col-md-7">

<img alt="marker-image" class="marker" src="http://i1292.photobucket.com/albums/b561/parisliahyun/ScreenShot2013-12-03at14241AM_zps0393dc45.png" style="margin-top: 10px" width="250px" height="200px"/>

<center>
  <div class="coin">
    <!-- <a href="#" data-toggle="tooltip" title="Drop me into the piggy bank."> -->
    <img id="draggable" src="http://www.greatnorthernprepper.com/wp-content/uploads/2012/11/Canadian-Gold-Maple-Leaf-Coin.png" height="120" width="120">
    <!-- </a> -->
  </div>
</center>

  <div id="droppable">
    <img alt="money-image" class="pig" src="http://cminfo.ca/wp-content/uploads/2013/07/smart-piggy-bank.jpg" style="margin-top: 10px" width="400px" height="400px"/>
  </div>

  <!-- <div class="info well"> -->
<table class="table">    
  <tbody>
    <tr class="stats-header">
    <th>Your current savings</th>
    <th>Goal name</th>
    <th>Your group's goal</th>
    <th>Your goal</th>
    <th>Description</th>
    <th>Deadline</th>
  </tr>
  <tr>
    <td><div class="balance"><%= @goal.balance(@current_user.id) %></div></td>
    <td><%= @goal.name %></td>
    <td>$<%= @goal.final_amount %></td>
    <td>$<%= @goal.individual_final_amount %></td>
    <td><%= @goal.description %></td>
    <td><%= @goal.transform_date %></td>
  </tr>
  </tbody>  
</table>
<!-- </div>  -->
  
</div>  


<div class="col-md-5 right-rail">
 
  <h5>STATS!</h5>
  <!-- INDIVIDUAL PROGRESS BARS -->

  <div class="chart well">
    <h4>Your progress:</h4>
    <div class="progress">
      <div class="progress-bar progress-bar-success individual" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: <%= @goal.progress[@current_user.id][:individual_progress] %>;background-color: <%= @goal.progress[@current_user.id][:color] %>">
        <span class="sr-only">40% Complete (success)</span>
      </div>
    </div>
  </div>

  <% if @goal.users.length > 1 %>


  <!-- EACH FRIEND'S PROGRESS BARS -->

  <div class="chart well">
    <h4>Each member's progress:</h4>
    <% @goal.users.each do |user| %>
    <div class="progress">
      &nbsp &nbsp <span class="display-name"><strong><%= user.first_name %></strong></span>
      <div class="progress-bar progress-bar-success bar<%= user.id %>" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: <%=@goal.progress[user.id][:individuals_progress_for_goal] %>;background-color: <%= @goal.progress[user.id][:color] %>">
        <span class="sr-only"><%= user.first_name %></span>
      </div>
      
    </div>
    <% end %> 
  </div>


<!-- GROUP PROGRESS BAR -->

<div class="chart well">
  <h4>Your group's progress so far:</h4>
  <div class="progress">
  <% @goal.users.each do |user| %>
    <div class="progress-bar progress-bar-success stacked<%= user.id %>" style="width: <%=@goal.progress[user.id][:individuals_progress_for_goal] %>;background-color: <%= @goal.progress[user.id][:color] %>">
      <span class="sr-only">35% Complete (success)</span>
    </div>
  <% end %> 
  </div>


<% end %>

</div> 

</div>


<!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Save some MOOLAH!</h4>
        </div>

          <div class="modal-body">
              
              <center>
              <%= form_tag user_goal_transactions_path(@current_user, @goal), :action => :post, :html => {:class => 'form',:role => 'form'} do %>

                <div class="form-transaction">
                  <%= text_field_tag :description, nil, {placeholder: "description", class: 'field'} %></br>
                </div>

                <div class="form-group">
                  <%= text_field_tag :amount, nil, {placeholder: "amount", class: 'field'} %></br>  
                </div>
    

          </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= submit_tag nil, class: "btn btn-primary" %>
          <% end %>
        </center>
      </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

<!-- Modal Penguin -->
  <div class="modal fade" id="penguin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">

          <div class="modal-body">
              
          <center>
          <h2 style="background-color: white !important">IT'S TIME FOR A FIESTA! You are now a:</h2>
          <img class="aimage" src="<%= image_path 'penguin.gif' %>"/>
          </center>
          </div>
      </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

<!-- Modal Meerkat -->

  <div class="modal fade" id="meerkat" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">

          <div class="modal-body">
              
          <center>
          <h2 style="background-color: white !important">MOOLAH MOOLAH MOOLAH! You are now a:</h2>
          <img class="aimage" src="<%= image_path 'meerkat.gif' %>"/>
          </center>
          </div>
      </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->


  <!-- Modal Gorilla -->

    <div class="modal fade" id="gorilla" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">


          <div class="modal-body">
              
          <center>
          <h2 style="background-color: white !important">BANANA-RAMA! You've just reached another goal! You are now a:</h2>
          <img class="aimage" src="<%= image_path 'gorilla.gif' %>"/>
          </center>
          </div>
      </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->


  <!-- Modal Yak -->

    <div class="modal fade" id="yak" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <!-- <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">IT WORKS!</h4>
        </div> -->

          <div class="modal-body">
              
          <center>
          <h2 style="background-color: white !important">COIN-ICHIWA! Looks like you're done ya little:</h2>
          <img class="aimage" src="<%= image_path 'yak.gif' %>"/>
        </center>

          </div>
      </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

  
</div>

<script>
  var oldAchievement = <%= @oldAchievement.length %>;

  window.onload = function() {

      $( "#draggable" ).draggable();
      $( "#droppable" ).droppable({
        drop: function() {
          $('#draggable').fadeOut(200);
          $('#myModal').delay(400).modal('show');
        }
      });

      addedAmount = 0;

      bindForm();
    }

    function bindForm() {
      $("form").on("submit", function(e) {
        e.preventDefault();
        var val = $("input#amount").val();
        addedAmount += parseFloat(val);

        $.ajax({
          url: "<%= user_goal_transactions_path(@current_user, @goal) %>",
          type: "POST",
          data: "transaction[" + $(this).serialize(),
          context: this,
          success: function(response){ calcAchievements(response); updateProgress(addedAmount); }
        });
      });
    }

    function updateProgress(addedAmount) {
      var newSavings = (addedAmount + <%= @goal.balance(@current_user.id) %>);
      var iPercentage = ((newSavings / <%= @goal.individual_final_amount %> ) * 100) + "%";
      var gPercentage = ((newSavings / <%= @goal.final_amount %> ) * 100) + "%";


      var $iProgress = $('.individual');
      $iProgress.css("width", iPercentage);

      var $gProgress = $(".stacked<%= @current_user.id %>");
      $gProgress.css("width", gPercentage );

      var $bProgress = $(".bar<%= @current_user.id %>");
      $bProgress.css("width", gPercentage);


      $('#myModal').modal('hide');
      $("input#amount").val(null);
      $("input#description").val(null);
      $('#draggable').fadeIn(200);
      $('#draggable').css("top", "50px");

      var $balance = $('.balance');
      $balance.html("$" + newSavings);
    }

    function calcAchievements(response){
      var json_response = response;
      console.log(json_response);
      var json_achievement = json_response[1].length
      var i = json_response[1].length - 1
      if (json_achievement >= 1) {
        var achievementName = json_response[1][i].name
        console.log(achievementName);

        if (oldAchievement < json_achievement) {
          showModal(achievementName);
        }
      }

    }

    function showModal(achievementName){
    switch (achievementName) {
      case "Penguin":
        $('#penguin').modal('show');
        break;
      case "Meerkat":
        $('#meerkat').modal('show');
        break;
      case "Gorilla":
        $('#gorilla').modal('show');
        break;
      case "Yak":
        $('#yak').modal('show');
        break;
      default:
        break;
      }
    }



</script>