config/routes.rb
MoolahMeerkat::Application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get]
  match 'auth/failure', to: redirect('/'), via: [:get]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get]
  
  root 'welcome#index'
  

  resources :users, except: [:index] do
    resources :activities, only: [:index]
    collection do
      get 'search'
    end

    resources :achievements, only: [:index, :show] do
    end

    resources :goals do
      resources :transactions do
      end
    end

    resources :connections, only: [:create, :index, :destroy] do
    end

  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" <%= link_to "MOOLAH", root_path %></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<!--    <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form> -->
      <%= form_tag search_users_path, method: :get, class: "navbar-form navbar-left" do %>
        <div class="form-group">
          <%= text_field_tag 'query', nil, placeholder: "Find friends...", class: "form-control" %>
          <%= submit_tag 'search', class:  "btn btn-default" %>
        </div>
      <% end %>

    <ul class="nav navbar-nav">
      <li class="active"></li>
      <% if current_user %>
      <li><%= link_to "My Profile", user_path(@current_user.id) %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Goals <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <% @current_user.goals.each do |goal| %>
            <li><%= link_to goal.name, user_goal_path(@current_user.id, goal.id) %></li>
          <% end %>
        </ul>
      </li>
      <li><%= link_to 'New Goal', new_user_goal_path(@current_user.id) %></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li class="nav-text"><a href="#">Welcome back <%= current_user.first_name %>!  </a></li>
            <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
          <% else %>
            <li><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %></li>
          <% end %>
    </ul>
        

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoolahMeerkat</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header'%>

    <!-- <div class="container"> -->
   
      <%= yield %>
      <%= render 'layouts/footer'%>

 <!-- ############# for droppable ############### -->     

  <script>
   
 
  </script>

  

    <!-- </div> -->
  </body>
</html>